---
version: '3'
networks:
    api:
        driver: bridge

services:
    api:
        container_name: kalaxia_game_api
        build: .
        networks:
            - api
        volumes:
            - ".:/go/src/kalaxia-game-api"
